// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vtqiuorxqszivlmgxwkw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ0cWl1b3J4cXN6aXZsbWd4d2t3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY5ODAxODMsImV4cCI6MjA3MjU1NjE4M30.OC3fkeK-Dl24zpEEtMtrVWWphfd82YhJFkpnidzGy3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});